server:
  port: 9208

spring:
  application:
    name: authorization-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG